### ISSUE TITLE
Set assets error 500

### ISSUE THREAD

**Issue by ognjen011** [OpenNMS/onmsctl#27]
Hello,

when i try and set gps coordinates i end up with error 500. Is below correct usage of the command?

onmsctl -p pass nodes assets set AB1235 latitude  48.858578
ERROR: Invalid Response: 500 Server Error
onmsctl -p pass nodes assets set AB1235 longitude 2.294485
ERROR: Invalid Response: 500 Server Error

I am running onms version 27.1.0

**Comment by agalue** [comment]
Keep in mind that for requisitioned nodes, the best approach is to update the requisition with the coordinates instead of doing it in the nodes directly. That's because Provisiond can override them depending on how it was configured.

When you see something like this, the best approach is checking `/var/log/opennms/web.log` to see more details about the exception.

However, I believe I can add some defensive code in `onmsctl` to avoid the problem you're seeing. The thing is, you're adding `AB1235` as the node identifier, which is incorrect. As the help described should be either the node ID or the `foreignSource:foreignID` combination. For instance:

```bash=
➜ onmsctl nodes assets set 2 latitude  48.858578
```

Or,

```bash=
➜ onmsctl nodes assets set Local:agalue-mbp latitude 48.858578
```

And that's because:

```bash=
➜  onmsctl nodes list
Node ID	Node Label	Foreign Source	Foreign ID	SNMP sysObjectID
2	agalue-mbp	Local		agalue-mbp
1	opennms		Local		opennms
```

In terms of updating the coordinates in the requisition where the node is defined:

```bash=
onmsctl provision asset set Local agalue-mbp latitude 48.858578
```

I hope that helps.
